### PR TITLE
Update graphviz to 2.38

### PR DESCRIPTION
**Pull request by ForNeVeR**
Hello, I've updated the Graphviz package to 2.38. Would you please merge my pull request and push the package to Chocolatey?

BTW, I've tried to contact you through Chocolatey site and got no response. You should maybe check your email settings on the Chocolatey site.

### CODE REVIEW

**Comment by jden** [comment]
Oh, hi! Thanks for the pull request. I haven't received any emails from Chocolately. I don't use the project anymore - would you be interested in taking over the graphviz package? I can merge this PR but I don't have the ability to push it to Chcolatey

**Comment by ForNeVeR** [comment]
Yeah, I would like to maintain this package. How can you share package ownership with me on chocolatey.org? Is it an automated process or do we need to contact admins?

**Comment by jden** [comment]
l was able to log in to my chocolatey.org account and can add you as a
maintainer to transfer the package. What is your chocolatey username?

On Tuesday, January 6, 2015, Friedrich von Never <notifications@github.com>
wrote:

> Yeah, I would like to maintain this package. How can you share package
> ownership with me on chocolatey.org? Is it an automated process or do we
> need to contact admins?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jden/ChocoPackages/pull/3#issuecomment-68854356>.
>


-- 
Sent from Gmail Mobile

**Comment by ForNeVeR** [comment]
https://chocolatey.org/profiles/ForNeVeR

**Comment by jden** [comment]
OK, I've added you as a maintainer. Please let me know if you need anything
more on my end. Thanks for taking this on!

On Tuesday, January 6, 2015, Friedrich von Never <notifications@github.com>
wrote:

> https://chocolatey.org/profiles/ForNeVeR
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jden/ChocoPackages/pull/3#issuecomment-68862045>.
>


-- 
Sent from Gmail Mobile

**Comment by ForNeVeR** [comment]
Yeah, thank you!

**Pull request closed without merging**
